### ISSUE TITLE
Focus distance information?

### ISSUE THREAD

**Issue by jadware** [coral/freemote#5]
Do you know if it's possible to get the current focal distance, aperture, etc info from the camera?  Given we can step the focus and zoom by sending commands, one would presume this information may be available.  It does appear to be available in the Sony Wi-Fi protocol.

**Comment by coral** [comment]
@jadware 

Bluetooth Remote protocol does not expose it.

There is an undocumented protocol which Sony has never shipped a product for that is theorized to act as a bridge towards the same parameters as the wifi protocol but yeah it's... undocumented and noone knows :D
